/*
INSERT INTO로 다른테이블에있는 정보를 새로만든 테이블에 옮겨주는 작업할때 타입,크기,순서 다 정확히 대응되어야한다.

그래서 이러한 과정이 귀찮으면 INSERT ALL을 사용한다.
기존에 생성되있던 테이블을 참조하는것. 
WHERE조건으로 1 = 0 같은걸 걸어서 테이블 구조만 복제하기위해서 값은 빼고 구조만 복제하는것

*/

SELECT 'Hello' FROM DUAL;

CREATE TABLE EMP_COMMISSION
	AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT
  FROM EMPLOYEES;
 
CREATE TABLE EMP_NO_COMMISSION
	AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
  FROM EMPLOYEES;
  
SELECT * FROM USER_ALL_TABLES WHERE TABLE_NAME = 'EMP_COMMISSION';
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'EMP_COMMISSION';
SELECT * FROM USER_COL_COMMENTS WHERE TABLE_NAME = 'EMP_COMMISSION';
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMP_COMMISSION';

SELECT * FROM USER_ALL_TABLES WHERE TABLE_NAME = 'EMP_NO_COMMISSION';
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'EMP_NO_COMMISSION';
SELECT * FROM USER_COL_COMMENTS WHERE TABLE_NAME = 'EMP_NO_COMMISSION';
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMP_NO_COMMISSION';