CREATE TABLE COMMENTS(
	   ID NUMBER
	 , BID NUMBER
	 , EMPID NUMBER
	 , CONTENT VARCHAR2(1000) NOT NULL
	 , CREATEDATE DATE DEFAULT(SYSDATE)
	 , DELETED VARCHAR2(1) CHECK( DELETED IN ('Y', 'N'))
	 , HIDDEN VARCHAR2(1) CHECK( HIDDEN IN ('Y', 'N'))
	 , LIKECNT NUMBER DEFAULT(0)
	 , CONSTRAINT COMMENTS_ID_PK PRIMARY KEY (ID)
	 , CONSTRAINT COMMENTS_BID_FK FOREIGN KEY (BID) REFERENCES EMP_BOARDS(ID)
	 , CONSTRAINT COMMENTS_EMPID_FK FOREIGN KEY (EMPID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
	 );
	 
SELECT * FROM COMMENTS;
DELETE FROM COMMENTS;

CREATE SEQUENCE COMMENTS_SEQ NOCACHE;

