DROP SEQUENCE EMP_BOARDS_SEQ;

CREATE TABLE EMP_BOARDS (
	ID NUMBER NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(2000),
	EMPID NUMBER NOT NULL,
	CREATEDATE DATE DEFAULT(SYSDATE),
	VIEW_CNT NUMBER DEFAULT(0),
	"LIKE" NUMBER DEFAULT(0),
	CONSTRAINT EMP_BOARDS_ID_PK PRIMARY KEY (ID),
	CONSTRAINT EMP_BOARDS_EMPID_FK FOREIGN KEY(EMPID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

CREATE SEQUENCE EMP_BOARDS_SEQ NOCACHE; --NEXTSEQ에서 사용하는 시퀀스

SELECT * FROM EMP_BOARDS;

--ERD다이어그램 수정내용(좋아요, 조회수)
ALTER TABLE EMP_BOARDS ADD VIEW_CNT NUMBER DEFAULT(0);
ALTER TABLE EMP_BOARDS ADD "LIKE" NUMBER DEFAULT(0);

CREATE TABLE EMP_BOARDS_STATICS(
	   ID NUMBER PRIMARY KEY,
	   EMPID NUMBER,
	   BID NUMBER,
	   VIEWED VARCHAR2(1) CHECK(VIEWED IN('Y', 'N')),
	   LATEST_VIEW_DATE DATE,
	   LIKED VARCHAR2(1) CHECK(LIKED IN('Y', 'N')),
	   CONSTRAINT EMP_BOARDS_STATICS_EMPID_FK FOREIGN KEY(EMPID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
	   CONSTRAINT EMP_BOARDS_STATICS_BID_FK FOREIGN KEY(BID) REFERENCES EMP_BOARDS(ID)
);
DROP TABLE EMP_BOARDS_STATICS;

CREATE SEQUENCE EMP_BOARDS_STATICS_SEQ;
DROP SEQUENCE EMP_BOARD_STATICS_SEQUENCE;

SELECT * FROM EMPLOYEES;
SELECT * FROM EMP_BOARDS;
SELECT * FROM EMP_BOARDS_STATICS;

ALTER TABLE EMP_BOARDS_STATICS ADD LIKED VARCHAR2(1) CHECK(LIKED IN('Y', 'N'));

UPDATE EMP_BOARDS_STATICS 
   SET LIKED = 'N';
   
DELETE 
  FROM EMP_BOARDS
 WHERE ID = 1;