DROP SEQUENCE EMP_BOARDS_SEQ;

CREATE TABLE EMP_BOARDS (
	ID NUMBER NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(2000),
	EMPID NUMBER NOT NULL,
	CREATEDATE DATE DEFAULT(SYSDATE),
	VIEW_CNT NUMBER DEFAULT(0),
	"LIKE" NUMBER DEFAULT(0),
	CONSTRAINT EMP_BOARDS_ID_PK PRIMARY KEY (ID),
	CONSTRAINT EMP_BOARDS_EMPID_FK FOREIGN KEY(EMPID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

CREATE SEQUENCE EMP_BOARD_SEQ NOCACHE;

SELECT * FROM EMP_BOARDS;

--ERD다이어그램 수정내용(좋아요, 조회수)
ALTER TABLE EMP_BOARDS ADD VIEW_CNT NUMBER DEFAULT(0);
ALTER TABLE EMP_BOARDS ADD "LIKE" NUMBER DEFAULT(0);