CREATE TABLE T_MYBATIS (
	   id NUMBER
	 , name VARCHAR2(100)
	 , today DATE
);

ALTER TABLE T_MYBATIS ADD CONSTRAINT T_MYBATIS_ID_PK PRIMARY KEY(ID);

SELECT * FROM T_MYBATIS;
DELETE FROM T_MYBATIS;

CREATE SEQUENCE SEQ_MYBATIS;

INSERT INTO T_MYBATIS VALUES(SEQ_MYBATIS.NEXTVAL, 'test', SYSDATE)

SELECT * FROM T_MYBATIS;
DELETE FROM T_MYBATIS;

SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , SALARY 
  FROM EMPLOYEES
 WHERE SALARY >= 10000
   AND DEPARTMENT_ID IN (80, 90, 100)
   AND HIRE_DATE BETWEEN TO_DATE('1990/01/01') AND TO_DATE('1999/12/31'); 
   
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

SELECT COUNT(*) AS TOTAL
	 , D.DEPARTMENT_NAME
	 , D.DEPARTMENT_ID
  FROM EMPLOYEES E
  JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
-- WHERE D.DEPARTMENT_ID = 30
-- WHERE D.DEPARTMENT_ID IN (10, 20, 30, 40)
 WHERE D.DEPARTMENT_ID BETWEEN 10 AND 40
 GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME;
