CREATE OR REPLACE FUNCTION FUNC_TEST1(V1 NUMBER) RETURN NUMBER 
IS 
BEGIN 
	RETURN V1 + 10;
END;

SELECT FUNC_TEST1(5) FROM DUAL;


CREATE OR REPLACE FUNCTION FUNC_TEST2(V1 VARCHAR2) RETURN VARCHAR2 
IS 
BEGIN 
	RETURN V1 || ' Done !!';
END;

SELECT FUNC_TEST2('Hello') FROM DUAL;


CREATE OR REPLACE FUNCTION FUNC_TEST3(V1 VARCHAR2, V2 VARCHAR2) RETURN VARCHAR2 
IS 
	var VARCHAR2(10) := ' Done!';
BEGIN 
	RETURN V1 || V2 || var ;
END;

SELECT FUNC_TEST3('Hello', 'World') FROM DUAL;

