CREATE TABLE DEPARTMENT(
    DEPTCODE NUMBER PRIMARY KEY,
    DEPTNAME NVARCHAR2(10) NOT NULL
);

CREATE TABLE EMPLOYEE(
    EMPNO NUMBER PRIMARY KEY,
    EMPNAME VARCHAR2(10) NOT NULL,
    DEPTNO NUMBER REFERENCES DEPARTMENT(DEPTCODE)
);

SELECT EMPNO, EMPNAME, DEPTNO, DEPTNAME
  FROM EMPLOYEE
  JOIN DEPARTMENT ON(DEPTNO = DEPTCODE);